import { makeStyles } from 'tss-react/mui';

export const useStyles = makeStyles()((theme) => ({
  root: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100vh',
    backgroundColor: theme.palette.background.default,
    color: theme.palette.colors.gray[900],
    position: 'relative' as const,
    padding: '24px',
  },
  topIcon: {
    position: 'absolute' as const,
    top: '32px',
    left: '32px',
    color: theme.palette.colors.gray[900],
  },
  topRightActions: {
    position: 'absolute' as const,
    top: '24px',
    right: '24px',
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    zIndex: 10,
  },
  signOutLink: {
    fontFamily: 'Graphik',
    fontSize: '14px',
    fontWeight: 500,
    color: theme.palette.colors.gray[500],
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    '&:hover': {
      color: theme.palette.colors.gray[900],
      textDecoration: 'underline',
    },
  },
  bottomImage: {
    position: 'absolute' as const,
    bottom: '0px',
    left: 0,
    width: '100%',
    height: '180px',
    backgroundImage: 'url(https://amura.ai/wp-content/uploads/2021/03/wavesnew.png)',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'bottom',
    backgroundSize: '100%',
    pointerEvents: 'none' as const,
  },
  card: {
    width: '100%',
    maxWidth: 480,
    backgroundColor: theme.palette.colors.system.white,
    borderRadius: '12px',
    padding: '40px 36px',
    boxShadow: '0px 2px 12px rgba(0, 0, 0, 0.06)',
    position: 'relative' as const,
    zIndex: 1,
    '@media (max-width: 480px)': {
      padding: '28px 20px',
    },
  },
  heading: {
    fontFamily: 'Graphik',
    fontSize: '22px',
    lineHeight: '28px',
    fontWeight: 600,
    color: theme.palette.colors.gray[900],
    margin: 0,
  },
  subheading: {
    fontFamily: 'Graphik',
    fontSize: '14px',
    lineHeight: '20px',
    fontWeight: 400,
    color: theme.palette.colors.gray[500],
    margin: '6px 0 0 0',
  },
  divider: {
    height: '1px',
    backgroundColor: theme.palette.colors.gray[100],
    margin: '24px 0 20px 0',
  },
  tenantList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '16px',
    maxHeight: '420px',
    overflowY: 'auto',
    paddingRight: '4px',
    marginBottom: '24px',
  },
  tenantBlock: {
    display: 'flex',
    flexDirection: 'column' as const,
  },
  tenantHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '6px 4px',
    margin: 0,
    cursor: 'pointer',
    userSelect: 'none' as const,
    fontFamily: 'Graphik',
    fontSize: '15px',
    fontWeight: 600,
    color: theme.palette.colors.gray[900],
    borderRadius: '6px',
    transition: 'background-color 0.15s ease',
    '&:hover': {
      backgroundColor: theme.palette.colors.gray[25],
    },
    '&:focus-visible': {
      outline: `2px solid ${theme.palette.colors.gray[300]}`,
      outlineOffset: '2px',
    },
  },
  tenantChevron: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: theme.palette.colors.gray[500],
    width: '20px',
    height: '20px',
  },
  tenantName: {
    fontFamily: 'Graphik',
    fontSize: '15px',
    fontWeight: 600,
    color: theme.palette.colors.gray[900],
  },
  tenantCount: {
    fontFamily: 'Graphik',
    fontSize: '14px',
    fontWeight: 400,
    color: theme.palette.colors.gray[500],
  },
  tenantServices: {
    display: 'flex',
    flexDirection: 'column' as const,
    paddingLeft: '28px',
    marginTop: '4px',
  },
  serviceRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '10px 12px',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'background-color 0.15s ease',
    '&:hover': {
      backgroundColor: theme.palette.colors.gray[25],
    },
  },
  serviceRowSelected: {
    backgroundColor: theme.palette.colors.gray[50],
    '&:hover': {
      backgroundColor: theme.palette.colors.gray[50],
    },
  },
  radioOuter: {
    width: '16px',
    height: '16px',
    borderRadius: '50%',
    border: `1.5px solid ${theme.palette.colors.gray[300]}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    transition: 'border-color 0.15s ease',
  },
  radioOuterSelected: {
    borderColor: theme.palette.colors.gray[900],
  },
  radioInner: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: theme.palette.colors.gray[900],
  },
  serviceLabel: {
    fontFamily: 'Graphik',
    fontSize: '15px',
    lineHeight: '20px',
    fontWeight: 400,
    color: theme.palette.colors.gray[900],
  },
  emptyState: {
    fontFamily: 'Graphik',
    fontSize: '14px',
    lineHeight: '20px',
    fontWeight: 400,
    color: theme.palette.colors.gray[500],
    textAlign: 'center' as const,
    padding: '24px 0',
  },
  errorMessage: {
    fontFamily: 'Graphik',
    fontSize: '13px',
    lineHeight: '18px',
    color: '#ff6060',
    textAlign: 'center' as const,
    margin: '0 0 16px 0',
  },
  nextButton: {
    height: '48px',
    borderRadius: '8px',
    fontFamily: 'Graphik',
    fontSize: '15px',
    fontWeight: 600,
    textTransform: 'none' as const,
    backgroundColor: '#3D3D3D',
    color: theme.palette.colors.system.white,
    '&:hover': {
      backgroundColor: '#2A2A2A',
    },
    '&.Mui-disabled': {
      backgroundColor: '#D6D6D6',
      color: '#9E9E9E',
    },
  },
  loadingWrap: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '200px',
  },
}));
